### ISSUE TITLE
master mergeのタイミングでlambdaにデプロイする

### ISSUE THREAD

**Issue by ShuzoN** [ShuzoN/zut#13]
ラムダにデプロイ手動で zip -> lambda deployしてて面倒なのでgithub actionsでデプロイしたい

**Comment by ShuzoN** [comment]
https://qiita.com/homines22/items/412d4e81b24804d75205

**Comment by ShuzoN** [comment]
lambdaデプロイ用のIAMを作る必要があるのだけども、IAMの権限設定周り詳しくないな...
どこみればいいんやろ

**Comment by ShuzoN** [comment]
https://github.com/marketplace/actions/aws-lambda-deploy

**Comment by IkezoeMakoto** [comment]
lambdaからソースコードの指定をs3見るようにして`make deploy`でs3でzipをアップロードできるようにしておいてから
github actionsから`make deploy`実行できるようにすれば行けるはず

https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/gettingstarted-package.html#gettingstarted-package-awsother

**Comment by ShuzoN** [comment]
https://www.youtube.com/watch?v=UQiRhKgQ5X0

**Comment by ShuzoN** [comment]
https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/install-cliv2-mac.html#cliv2-mac-install-cmd

awscli2を手元にinstall


```sh

// busketの作成
$ aws s3 mb s3://zut --profile=shuzon --region=ap-northeast-1

// zipをupload
$ aws s3 mv zut.zip s3://zut
move: ./zut.zip to s3://zut/zut.zip

// busket ls 
$ aws s3 ls s3://zut
2021-06-05 20:49:48   37518742 zut.zip

```

**Comment by ShuzoN** [comment]
putだけ許容したユーザを作成 `zut-deploy`

![image](https://user-images.githubusercontent.com/5877377/120893376-f8918580-c64d-11eb-869f-add2730d12f0.png)
![image](https://user-images.githubusercontent.com/5877377/120893394-1828ae00-c64e-11eb-8fe0-c8866e4f5310.png)

**Comment by ShuzoN** [comment]
repositoryに環境変数振った


![スクリーンショット 2021-06-05 22 59 35](https://user-images.githubusercontent.com/5877377/120894124-d8fc5c00-c651-11eb-84f5-73efc5ea58ce.png)

**Comment by ShuzoN** [comment]
![スクリーンショット 2021-06-05 23 24 54](https://user-images.githubusercontent.com/5877377/120894798-48277f80-c655-11eb-8f6e-7d1990cda97c.png)

めっちゃ失敗してるやん

> Failed to resolve action download info. Error: Unable to resolve action `actions/aws@master`, repository not found


https://github.com/aws-actions/configure-aws-credentials

どうも全然違うっぽいな

```
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://my-s3-test-website-bucket

    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync . s3://my-s3-prod-website-bucket

```
