### ISSUE TITLE
github actionsの追加

### ISSUE THREAD

**Issue by ShuzoN** [ShuzoN/zut#22]
github actions で ci 回す。といっても `make test` するくらいだけども。

slackの通知も入れてくれてええんやで
https://qiita.com/progrhyme/items/badf31978612b22dbf47

**Comment by ShuzoN** [comment]
こんな感じで動くはず

```
name: CI

on: [push]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      - run: make hoge
```
